---

- hosts: all

  vars:
    web_data: www-data
    gen_passwd: "azureuser!@t"

  tasks:

    - name: download docker demon
      command: curl -fsSL https://get.docker.com -o get-docker.sh

    - name: move get-docker.sh
      command: mv /root/get-docker.sh /home/azureuser

    - name: change docker.sh own
      file:
        path: /home/azureuser/get-docker.sh
        state: file
        mode: '0700'
        owner: azureuser
        group: azureuser


    - name: install docker demon
      shell: /home/azureuser/get-docker.sh
      async: 2100
      poll: 0
      register: docker


    - name: Check if docker install is complete
      async_status:
        jid: "{{ docker.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 10
      retries: 300

    # sudo groupadd docker
    - name: Create "docker" group
      group:
        name: "docker"
        state: present

    - name: add remote azureuser user to docker group
      user:
        name: "azureuser"
        groups: "docker"
        append: yes

    - name: restart the docker services
      command: service docker restart